# docker-compose.yml
services:
  db:
    container_name: django-db
    image: ankane/pgvector
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web:
    container_name: django-web
    build: ./server/.
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/code
    ports:
      - 8000:8000
    depends_on:
      - "db"
  
  client:
    container_name: streamlit-client
    build: ./client/.
    command: streamlit run /code/app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./client:/code
    ports:
      - 8501:8501
    depends_on:
      - "web"

networks:
  default:

volumes:
  postgres_data:
