# Generated by Django 5.0.3 on 2024-03-21 03:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rfp_api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
