# Generated by Django 5.0.2 on 2024-03-28 06:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfp_api", "0002_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ticket_number", models.UUIDField(default=uuid.uuid4)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("accepted_date", models.DateTimeField(blank=True, null=True)),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "ticket_status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Completed", "Completed"), ("Pending", "Pending")],
                        max_length=15,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="rfp_api.organization"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by",
                        to="rfp_api.organization",
                    ),
                ),
            ],
        ),
    ]
