# Generated by Django 5.0.3 on 2024-03-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp_api', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('answer_id', models.IntegerField(null=True)),
                ('question_id', models.IntegerField(null=True)),
            ],
        ),
    ]
