# Generated by Django 5.0.2 on 2024-04-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfp_api', '0003_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
    ]
