# Generated by Django 5.0.3 on 2024-04-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfp_api", "0005_ticket_answer_id_ticket_question_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="auto_generated",
            field=models.BooleanField(default=False),
        ),
    ]
