# Generated by Django 5.0.4 on 2024-04-16 14:40

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rfp_api", "0006_ticket_auto_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="vector_embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
